<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="umesh" ignored="1" name="validating user login and managerHomePage title(failed)" tests="1" failures="1" timestamp="2020-09-19T14:14:41 IST" time="69.224" errors="0">
  <testcase name="titleTest" time="1.79" classname="com.netBankingTestCases.TC_LoginTest_001">
    <failure type="java.lang.AssertionError" message="credential is invalid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: credential is invalid expected [true] but found [false]
at com.netBankingTestCases.TC_LoginTest_001.titleTest(TC_LoginTest_001.java:79)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- titleTest -->
  <testcase name="loginTest" time="0.0" classname="com.netBankingTestCases.TC_LoginTest_001">
    <ignored/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- validating user login and managerHomePage title(failed) -->
